afkWarningTime: 60 # 60 секунд ничего не делать до предупреждающего сообщения
afkKickTime: 120 # 120 секунд после предупреждающего сообщения. После - кик
afkWarningMessage: "&eВы стоите в AFK. Через 2 минуты Вас кикнут."
afkKickMessage: "&cВы стояли в AFK"
reloadMessage: "&aКонфигурация плагина EuphoricAFK перезагружена."